theme: jekyll-theme-slate
title: Tanner Hamilton | Software Developer Portfolio
description: A portfolio showcasing my work in [Specific Tech 1] and [Specific Tech 2].
author: Tanner Hamilton
header_pages:
  - about.md
  - projects.md

color: green

source: .

exclude:
  - README.md
